apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: githab-push-binding
spec:
  params:
  - name: gitrevision
    value: $(body.after)
  - name: gitrepositoryurl
    value: $(body.clone_url)
