apiVersion: v1
kind: Secret
metadata:
  name: githab-auth
  annotations:
    tekton.dev/git-0: http://git.k8s.local
type: kubernetes.io/basic-auth
stringData:
  username: lenkac
  password: yylian2016
